//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteInProgress
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class ImageGallery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ImageGallery()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
            this.Categories = new HashSet<Category>();
        }

        public int FileID { get; set; }
        public int FileSize { get; set; }
        public string FileName { get; set; }
        public byte[] FileData { get; set; }
        public string UserID { get; set; }
        public System.DateTime DateOfPosting { get; set; }
        public string Title { get; set; }
        [Display(Name = "Category Name")]
        public int CategoryId { get; set; }
        [Display(Name = "Information about your drink")]
        public string Info { get; set; }
        [Display(Name = "Telephone number")]
        public string Tel { get; set; }
        [Display(Name = "Please select a picture")]
        public HttpPostedFileBase File { get; set; }
        public string City { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Categories { get; set; }
    }
}
