//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteInProgress
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class ImageGallery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ImageGallery()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
        }
    
        public int FileID { get; set; }
        public int FileSize { get; set; }
        public string FileName { get; set; }
        public byte[] FileData { get; set; }
        public string UserID { get; set; }
        public System.DateTime DateOfPosting { get; set; }
        public string Title { get; set; }
        [Display(Name="Subject Name")]
        public int CategoryId { get; set; }
        [Display(Name ="Please choose a picture")]
        public HttpPostedFileBase File { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
    }
}
