//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteInProgress
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class ImageGallery
    {
        public int FileID { get; set; }
        public int FileSize { get; set; }
        public string FileName { get; set; }
        public byte[] FileData { get; set; }
        public string UserID { get; set; }
        public DateTime DateOfPosting { get; set; }


        [Display(Name = "Upload an Image")]
        public HttpPostedFileBase File { get; set; }

        public string Title { get; set; }
    }
}
